/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [loan_key]
      ,[is_current]
      ,[start_date]
      ,[end_date]
      ,[entity_code]
      ,[branch_key]
      ,[currency_code]
      ,[refinanced]
      ,[rebuild_no]
      ,[previous_contract_number]
      ,[product_key]
      ,[interest_rate]
      ,[grace_period]
      ,[disbursment_dateid]
      ,[principal_amount]
      ,[interest_planned_amount]
      ,[principal_amount_lccy]
      ,[interest_planned_amount_lccy]
      ,[principal_amount_eur]
      ,[interest_planned_amount_eur]
      ,[maturity_dateid]
      ,[loan_term]
      ,[modification_dateid]
      ,[modification_timestamp]
      ,[loan_officer_user_code]
  FROM [Customer Ageing Data].[dbo].[Customer Ageing $]